### ISSUE TITLE
the clock doesn't stay on top

### ISSUE THREAD

**Issue by Sneaken** [robert-wallis/Clock-On-Top#1]
When I open an app in full screen, the clock doesn't stay on top. can u help me ?

and some time the clock not working but not throw error, i can not find clock anywhere.

Below is my device information:
macOS 12.6
Apple M1 Max 

thank you!

**Comment by Sneaken** [comment]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/37062838/191703800-afe3c1b6-3474-421c-8d32-af99b540e50a.png">

**Comment by robert-wallis** [comment]
I have the same issue.  This needs to be fixed.

When I loose the clock I have to close it from the dock by right clicking on the dock icon and choosing Quit.
😢

**Comment by Sneaken** [comment]
I tried many times and found that switching the resolution will make it appear.

you can try it.

**Comment by Sneaken** [comment]
But I don't know how to fix it, I'm new to Swift  👀

**Comment by robert-wallis** [comment]
I think this may have been solved with [release v0.5](https://github.com/robert-wallis/Clock-On-Top/releases/tag/v0.5) please re-open if this does not solve your issue.

Sorry to trouble you 麻烦你
- Robert
